### ISSUE TITLE
Proguard configuration

### ISSUE THREAD

**Issue by emartynov** [Ashok-Varma/Gander#22]
I just tried obfuscated build and got a crash:

```
java.lang.NullPointerException: Attempt to invoke interface method 'com.ashokvarma.gander.internal.data.TransactionDao com.ashokvarma.gander.internal.data.GanderStorage.getTransactionDao()' on a null object reference
        at com.ashokvarma.gander.GanderInterceptor.create(GanderInterceptor.java:284)
        at com.ashokvarma.gander.GanderInterceptor.createTransactionFromRequest(GanderInterceptor.java:215)
        at com.ashokvarma.gander.GanderInterceptor.intercept(GanderInterceptor.java:154)
        at com.mycomp.common.network.proxy.ProxyOnSubscribe.callProxyRequest(ProxyOnSubscribe.java:141)
        at com.mycomp.common.network.proxy.ProxyOnSubscribe.callProxyRequestAndNotifyEmitter(ProxyOnSubscribe.java:108)
        at com.mycomp.common.network.proxy.ProxyOnSubscribe.subscribe(ProxyOnSubscribe.java:53)
        at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

Would be great to have simple proguard configuration added to prevent it.

**Comment by Ashok-Varma** [comment]
that's not due to obfuscation emartynov. 
3.0.0 changelog needs the storage to be declared. Just added changelog please refer https://github.com/Ashok-Varma/Gander/releases

**Comment by emartynov** [comment]
Yeah! I found it is just a migration issue. Thanks!

**Comment by Aksz1988** [comment]
i got a fabric issue, unable to find

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Integer com.ashokvarma.gander.internal.data.b.p()' on a null object reference
       at com.ashokvarma.gander.internal.support.GanderColorUtil.a + 17(GanderColorUtil.java:17)
       at com.ashokvarma.gander.internal.support.GanderColorUtil.a + 1(GanderColorUtil.java:1)
       at com.ashokvarma.gander.internal.support.NotificationHelper.b + 2(NotificationHelper.java:2)
       at com.ashokvarma.gander.internal.support.NotificationHelper.a + 118(NotificationHelper.java:118)
       at com.ashokvarma.gander.GanderInterceptor.a + 21(GanderInterceptor.java:21)
       at com.ashokvarma.gander.GanderInterceptor.a + 162(GanderInterceptor.java:162)
       at com.ashokvarma.gander.GanderInterceptor.intercept + 4(GanderInterceptor.java:4)
       at okhttp3.internal.http.RealInterceptorChain.a + 157(RealInterceptorChain.java:157)
       at okhttp3.internal.http.RealInterceptorChain.a + 6(RealInterceptorChain.java:6)
       at com.blackbooktravels.blackbook.data.network.ServiceGenerator$1.intercept + 4(ServiceGenerator.java:4)
       at okhttp3.internal.http.RealInterceptorChain.a + 157(RealInterceptorChain.java:157)
       at okhttp3.internal.http.RealInterceptorChain.a + 6(RealInterceptorChain.java:6)
       at okhttp3.RealCall.g + 115(RealCall.java:115)
       at okhttp3.RealCall$AsyncCall.c + 11(RealCall.java:11)
       at okhttp3.internal.NamedRunnable.run + 17(NamedRunnable.java:17)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1162(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 636(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run + 764(Thread.java:764)

**Comment by Aksz1988** [comment]
> Yeah! I found it is just a migration issue. Thanks!

what do you mean by migration

**Comment by Ashok-Varma** [comment]
#32
