### ISSUE TITLE
Specify PendingIntent mutability for Android 12

### ISSUE THREAD

**Issue by juliemovify** [Ashok-Varma/Gander#36]
To be able to target Android 12, all PendingIntent should have a specified mutability.
Reference:   https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability

```
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
        at android.app.PendingIntent.getActivity(PendingIntent.java:444)
        at android.app.PendingIntent.getActivity(PendingIntent.java:408)
        at com.ashokvarma.gander.internal.support.NotificationHelper.show(NotificationHelper.java:81)
        at com.ashokvarma.gander.GanderInterceptor.create(GanderInterceptor.java:287)
        at com.ashokvarma.gander.GanderInterceptor.createTransactionFromRequest(GanderInterceptor.java:215)
        at com.ashokvarma.gander.GanderInterceptor.intercept(GanderInterceptor.java:154)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

I could find the following references in the code:
https://github.com/Ashok-Varma/Gander/blob/94077c4d93094f0b019886c555361e6cad366965/gander/src/main/java/com/ashokvarma/gander/internal/support/NotificationHelper.java#L80-L86
Suggested solution: `.setContentIntent(PendingIntent.getActivity(mContext, 0, Gander.getLaunchIntent(mContext), PendingIntent.FLAG_IMMUTABLE))`
https://github.com/Ashok-Varma/Gander/blob/94077c4d93094f0b019886c555361e6cad366965/gander/src/main/java/com/ashokvarma/gander/internal/support/NotificationHelper.java#L121-L127
Suggested solution: `PendingIntent.getService(mContext, 11, deleteIntent, PendingIntent.FLAG_ONE_SHOT or PendingIntent.FLAG_IMMUTABLE)`
https://github.com/Ashok-Varma/Gander/blob/94077c4d93094f0b019886c555361e6cad366965/gander/src/main/java/com/ashokvarma/gander/internal/support/NotificationHelper.java#L129-L135
Suggested solution: `PendingIntent.getService(mContext, 12, dismissIntent, PendingIntent.FLAG_ONE_SHOT or PendingIntent.FLAG_IMMUTABLE)`

**Comment by dariusz-wiechecki-kbc** [comment]
That seems to be quite important fix for this library. For now e need to exclude it from our project because it is crashing at the launch. Fix is ready, so would be nice to get it merged and release a new version of the library :)

**Comment by dariusz-wiechecki-kbc** [comment]
That seems to be quite important fix for this library. For now we need to exclude it from our project because it is crashing at the launch. Fix is ready, so would be nice to get it merged and release a new version of the library :)

**Comment by juliemovify** [comment]
@dariusz-wiechecki-kbc I'm not sure this library is still maintained. If interested, take a look at [chucker](https://github.com/ChuckerTeam/chucker), it's based on the same parent repo and shows very similar features.
